es = {	
	'main.application.title': 'Primera Aplicacion con Ember.js',
	'index.login.fail': 'Los nombres no coinciden',
	'index.login.loginButton': 'Conectar',
	'index.login.nameLabel': 'Introduce tu nombre: ',
	'index.login.nameRepeatLabel': 'Repite tu nombre: ',
	'menu.login.noLog': 'No ha introducido ningun nombre',
	'menu.login.backToIndex': 'Volver',
	'menu.loged.welcomeMsg': 'Bienvenido',
	'menu.button.colorListButton': 'Ver Lista Colores',
	'menu.button.selectedColorButton': 'Ver Color Seleccionado',
	'menu.selectColor.selectColorText':'Seleccione un color: ',
	'menu.selectColor.selectedColorText':'Color Seleccionado: ',
	'menu.selectColor.selectColorButton':'Seleccionar',
	'menu.watchColor.selectedColorText':'Color Seleccionado: ',
	'menu.watchColor.selectColorButton':'Volver al menú',
};

en = {
	'main.application.title': 'First App with Ember.js',
	'index.login.fail': 'The names do not match',
	'index.login.loginButton': 'Sign in',
	'index.login.nameLabel': 'Type your name: ',
	'index.login.nameRepeatLabel': 'Re-type your name: ',
	'menu.login.noLog': 'You have to enter an username.',
	'menu.login.backToIndex': 'Back',
	'menu.loged.welcomeMsg': 'Welcome',
	'menu.button.colorListButton': 'Show color list',
	'menu.button.selectedColorButton': 'Selected color',
	'menu.selectColor.selectColorText':'Select a color: ',
	'menu.selectColor.selectedColorText':'Selected color: ',
	'menu.selectColor.selectColorButton':'Select',
	'menu.watchColor.selectedColorText':'Selected color: ',
	'menu.watchColor.selectColorButton':'Back to menu',
};